### ISSUE TITLE
needs linting

### ISSUE THREAD

**Issue by palash25** [vaibhavkandwal/square-fit-image#1]
Hi :wave: its always nice to see a junior pushing code to github. I came here through your psoc proposal 

Your code needs some stylistic changes (for example using parens in if statements is not very pythonic https://github.com/boxdox/square-fit-image/blob/master/dist/main.py#L53  ) for that you should follow [PEP8](https://www.python.org/dev/peps/pep-0008/) and run a linter against your code like https://github.com/ambv/black or http://coala.io/

**Comment by boxdox** [comment]
I hope this commit closes the issue. 061a9553a4d4fca6b92106ac661ae1c332b5332a

**Comment by palash25** [comment]
looks better and more readable than before, I hope you ran a linter instead of doing it manually (because in that case, you might miss a few lint errors)

Also, my recommendation would be to use vscode as your editor with Python language support extension enabled that will show you lint errors on the fly.
